name: Node-React.js CI


on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted
  
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node-React.js ${{matrix.node_version}}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{matrix.node_version}}
    - run: |
        cd api
        npm i
        cd ../ui
        npm i
        npm run build
