name: Node-React.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node-React.js ${{matrix.node_version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
      - run: |
          cd api
          npm i
          cd ../ui
          npm i
          npm run build
      - name: Create Archive
        run: tar -czvf build.tar.gz -C ./build
      - name: Deploy to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "build.tar.gz"
          target: "/var/www/node-react/_work/node-react"
