name: Node-React.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:  
      - name: Deploy to Remote Server
        run: |
          sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD1 }} scp -r ui/dist/* ${{ secrets.REMOTE_SERVER_USERNAME1 }}@${{ secrets.REMOTE_SERVER_HOST }}:/var/www/node-react/_work/node-react/node-react
