name: Node-React.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node-React.js ${{matrix.node_version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
      - run: |
          cd ui
          npm i
          npm run build    
      - name: Deploy to Remote Server
        run: |
          sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD1 }} scp -r ui/dist/* ${{ secrets.REMOTE_SERVER_USERNAME1 }}@${{ secrets.REMOTE_SERVER_HOST }}:/var/www/node-react/_work/node-react/node-react
